server:
  port: 8811

spring:
  application:
    name: skada-mng-service
  datasource:
    url: jdbc:mysql://localhost:3306/skada?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: 090763xiaoFENG
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j2.xml
